#!/bin/bash
# Quick Start Script - Migración Supabase

echo "🚀 MIGRACIÓN SUPABASE - QUICK START"
echo "==================================="
echo ""
echo "✅ Paso 1: Crear tablas en Supabase"
echo "   → Supabase Dashboard → SQL Editor"
echo "   → Copiar y ejecutar: scripts/001_create_tables.sql"
echo ""
echo "✅ Paso 2: Habilitar Realtime"
echo "   → Supabase Dashboard → Replication"
echo "   → Activar: products, quantity_variants, flavor_variants"
echo ""
echo "✅ Paso 3: Verificar conexión"
echo "   → Abre: http://localhost:3000/health"
echo "   → Debe mostrar todo verde ✓"
echo ""
echo "✅ Paso 4: Ejecutar migración"
echo "   → Abre: http://localhost:3000/migration"
echo "   → Haz clic en: Iniciar Migración"
echo "   → Espera a que complete"
echo ""
echo "✅ Paso 5: Usar Admin Panel"
echo "   → Abre: http://localhost:3000/admin"
echo "   → Crea/edita productos"
echo "   → Los cambios aparecen en tiempo real"
echo ""
echo "🎯 ¡Listo! Todos los productos están en Supabase."
echo ""
echo "📚 Para más info:"
echo "   - MIGRACION_GUIA.md (guía técnica)"
echo "   - CHECKLIST.md (pasos detallados)"
echo "   - EJEMPLOS.md (código de ejemplo)"
echo ""
echo "⏱️  Tiempo estimado: 30-40 minutos"
